dist: trusty
sudo: false

notifications:
  email: 
    recipients:
      - $EMAIL_NOTIFICATION
    on_success: always

language: node_js
node_js:
  - '8'

addons:

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ./travis/build-android.sh