dist: trusty
sudo: false

notifications:
  email: $EMAIL_NOTIFICATION

language: node_js
node_js:
  - '8'

addons:

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run clean
  - npm run lint
  - npm run build